server:
  port: 8000

eureka:
  instance:
    hostname : 13.125.181.139
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://13.125.181.139:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include:

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      routes:
        - id: Management-Service
          uri: http://3.35.179.234:8080/
          predicates:
            - Path=/api/**
        - id: User-Service
          uri: http://52.78.155.253:8081/
          predicates:
            - Path=/user-service/**
